"""“update_device_tracking_26-Oct”

Revision ID: 02b23419c9d6
Revises: 665d41ca6062
Create Date: 2025-10-26 03:21:42.742043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02b23419c9d6'
down_revision: Union[str, None] = '665d41ca6062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_violations',
    sa.Column('violation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('violation_type', sa.Enum('account_sharing', 'multiple_sessions', name='violation_types'), nullable=True),
    sa.Column('violation_count', sa.Integer(), nullable=True),
    sa.Column('first_violation', sa.DateTime(), nullable=True),
    sa.Column('last_violation', sa.DateTime(), nullable=True),
    sa.Column('is_device_banned', sa.Boolean(), nullable=True),
    sa.Column('ban_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('violation_id')
    )
    op.create_index(op.f('ix_device_violations_violation_id'), 'device_violations', ['violation_id'], unique=False)
    op.create_table('login_cooldowns',
    sa.Column('cooldown_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('cooldown_start', sa.DateTime(), nullable=True),
    sa.Column('cooldown_end', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('cooldown_id')
    )
    op.create_index(op.f('ix_login_cooldowns_cooldown_id'), 'login_cooldowns', ['cooldown_id'], unique=False)
    op.add_column('user_sessions', sa.Column('unique_session_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'user_sessions', ['unique_session_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_sessions', type_='unique')
    op.drop_column('user_sessions', 'unique_session_id')
    op.drop_index(op.f('ix_login_cooldowns_cooldown_id'), table_name='login_cooldowns')
    op.drop_table('login_cooldowns')
    op.drop_index(op.f('ix_device_violations_violation_id'), table_name='device_violations')
    op.drop_table('device_violations')
    # ### end Alembic commands ###
