"""update_16_July_2025

Revision ID: 0595f4f90b6d
Revises: 9f9c75c75e48
Create Date: 2025-07-16 04:30:19.814269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0595f4f90b6d'
down_revision: Union[str, None] = '9f9c75c75e48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('update_keys',
    sa.Column('key_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('key_id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_update_keys_key_id'), 'update_keys', ['key_id'], unique=False)
    op.create_table('user_notifications',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_user_notifications_notification_id'), 'user_notifications', ['notification_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_notifications_notification_id'), table_name='user_notifications')
    op.drop_table('user_notifications')
    op.drop_index(op.f('ix_update_keys_key_id'), table_name='update_keys')
    op.drop_table('update_keys')
    # ### end Alembic commands ###
