"""“update_transaction_1-Sep”

Revision ID: 1454d67e458e
Revises: 338ddd184ccb
Create Date: 2025-09-01 09:16:31.074073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1454d67e458e'
down_revision: Union[str, None] = '338ddd184ccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_sections', sa.Column('description', mysql.LONGTEXT(), nullable=True))
    op.add_column('questions', sa.Column('explanation', mysql.LONGTEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'explanation')
    op.drop_column('exam_sections', 'description')
    # ### end Alembic commands ###
