"""add dictation units and words tables

Revision ID: 2bb1bc7376ac
Revises: 4ac12923931a
Create Date: 2026-02-03 15:30:03.566051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bb1bc7376ac'
down_revision: Union[str, None] = '4ac12923931a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictation_units',
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('unit_id')
    )
    op.create_index(op.f('ix_dictation_units_unit_id'), 'dictation_units', ['unit_id'], unique=False)
    op.create_table('dictation_words',
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['dictation_units.unit_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('word_id')
    )
    op.create_index(op.f('ix_dictation_words_word_id'), 'dictation_words', ['word_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dictation_words_word_id'), table_name='dictation_words')
    op.drop_table('dictation_words')
    op.drop_index(op.f('ix_dictation_units_unit_id'), table_name='dictation_units')
    op.drop_table('dictation_units')
    # ### end Alembic commands ###
