"""add_is_important_to_dictation_words

Revision ID: 487dddb1971c
Revises: 2bb1bc7376ac
Create Date: 2026-02-04 11:22:52.913191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '487dddb1971c'
down_revision: Union[str, None] = '2bb1bc7376ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dictation_words', sa.Column('is_important', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dictation_words', 'is_important')
    # ### end Alembic commands ###
