"""add_saved_vocabulary_table

Revision ID: 4ac12923931a
Revises: 59009b85c58e
Create Date: 2026-01-28 10:36:47.695091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ac12923931a'
down_revision: Union[str, None] = '59009b85c58e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_vocabulary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=255), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Enum('listening', 'reading', name='vocab_source_types'), nullable=False),
    sa.Column('source_exam_id', sa.Integer(), nullable=True),
    sa.Column('source_exam_title', sa.String(length=255), nullable=True),
    sa.Column('is_important', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_vocabulary_id'), 'saved_vocabulary', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_vocabulary_id'), table_name='saved_vocabulary')
    op.drop_table('saved_vocabulary')
    # ### end Alembic commands ###
