"""“update_lis_forecast”

Revision ID: 5085e02001f5
Revises: 9e2f1a1dffd8
Create Date: 2025-11-19 09:09:09.600623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5085e02001f5'
down_revision: Union[str, None] = '9e2f1a1dffd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
