"""“update_highlight_11-Nov”

Revision ID: 5633c36cc026
Revises: 02b23419c9d6
Create Date: 2025-11-11 03:26:33.201286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5633c36cc026'
down_revision: Union[str, None] = '02b23419c9d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_highlights',
    sa.Column('highlight_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('result_id', sa.Integer(), nullable=True),
    sa.Column('part_number', sa.Integer(), nullable=True),
    sa.Column('highlighted_text', sa.Text(), nullable=True),
    sa.Column('range_info', sa.JSON(), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.exam_id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['exam_results.result_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('highlight_id')
    )
    op.create_index(op.f('ix_user_highlights_highlight_id'), 'user_highlights', ['highlight_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_highlights_highlight_id'), table_name='user_highlights')
    op.drop_table('user_highlights')
    # ### end Alembic commands ###
