"""“update_transaction_7-Sep”

Revision ID: 61488974bef2
Revises: 1454d67e458e
Create Date: 2025-09-07 01:39:12.246991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '61488974bef2'
down_revision: Union[str, None] = '1454d67e458e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('locate', mysql.LONGTEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'locate')
    # ### end Alembic commands ###
