"""“update_device_tracking_21-Oct”

Revision ID: 665d41ca6062
Revises: 61488974bef2
Create Date: 2025-10-21 03:12:21.867133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '665d41ca6062'
down_revision: Union[str, None] = '61488974bef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('device_info', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('login_time', sa.DateTime(), nullable=True),
    sa.Column('logout_time', sa.DateTime(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('session_token', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_user_sessions_session_id'), 'user_sessions', ['session_id'], unique=False)
    op.add_column('exam_results', sa.Column('attempt_number', sa.Integer(), nullable=False))
    op.add_column('listening_answers', sa.Column('result_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'listening_answers', 'exam_results', ['result_id'], ['result_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'listening_answers', type_='foreignkey')
    op.drop_column('listening_answers', 'result_id')
    op.drop_column('exam_results', 'attempt_number')
    op.drop_index(op.f('ix_user_sessions_session_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    # ### end Alembic commands ###
