"""“update_writing_tables”

Revision ID: 9e2f1a1dffd8
Revises: cc569140ed5c
Create Date: 2025-11-18 10:59:18.669706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e2f1a1dffd8'
down_revision: Union[str, None] = 'cc569140ed5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('writing_tasks', sa.Column('title', sa.String(length=200), nullable=True))
    op.add_column('writing_tasks', sa.Column('is_forecast', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('writing_tasks', 'is_forecast')
    op.drop_column('writing_tasks', 'title')
    # ### end Alembic commands ###
