"""“update_transaction_20_May”

Revision ID: 9f9c75c75e48
Revises: ab1ee58c148a
Create Date: 2025-05-20 07:07:37.028985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9f9c75c75e48'
down_revision: Union[str, None] = 'ab1ee58c148a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speaking_topics',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('topic_id')
    )
    op.create_index(op.f('ix_speaking_topics_topic_id'), 'speaking_topics', ['topic_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_active_student', sa.Boolean(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'student', 'customer', name='role_types'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('online', 'offline', name='user_status'), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.Column('is_vip', sa.Boolean(), nullable=True),
    sa.Column('vip_expiry', sa.DateTime(), nullable=True),
    sa.Column('account_activated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vip_packages',
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('package_type', sa.String(length=200), nullable=True),
    sa.Column('skill_type', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('package_id')
    )
    op.create_index(op.f('ix_vip_packages_package_id'), 'vip_packages', ['package_id'], unique=False)
    op.create_table('admin_notification_reads',
    sa.Column('read_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('notification_id', sa.String(length=255), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('item_id', sa.String(length=50), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('read_id')
    )
    op.create_index(op.f('ix_admin_notification_reads_read_id'), 'admin_notification_reads', ['read_id'], unique=False)
    op.create_table('exams',
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('exam_id')
    )
    op.create_index(op.f('ix_exams_exam_id'), 'exams', ['exam_id'], unique=False)
    op.create_table('speaking_questions',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('sample_answer', sa.Text(), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=True),
    sa.Column('part_type', sa.Enum('part1', 'part2', 'part3', name='speaking_part_types'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['speaking_topics.topic_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_index(op.f('ix_speaking_questions_question_id'), 'speaking_questions', ['question_id'], unique=False)
    op.create_table('vip_subscriptions',
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('payment_status', sa.Enum('pending', 'completed', 'reject', name='payment_status_types'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['vip_packages.package_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('subscription_id')
    )
    op.create_index(op.f('ix_vip_subscriptions_subscription_id'), 'vip_subscriptions', ['subscription_id'], unique=False)
    op.create_table('exam_access_types',
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('access_type', sa.Enum('no vip', 'vip', 'student', name='access_types'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.exam_id'], ),
    sa.PrimaryKeyConstraint('exam_id', 'access_type')
    )
    op.create_table('exam_results',
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('completion_date', sa.DateTime(), nullable=True),
    sa.Column('section_scores', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.exam_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('result_id')
    )
    op.create_index(op.f('ix_exam_results_result_id'), 'exam_results', ['result_id'], unique=False)
    op.create_table('exam_sections',
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('section_type', sa.String(length=255), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('total_marks', sa.Float(), nullable=True),
    sa.Column('order_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.exam_id'], ),
    sa.PrimaryKeyConstraint('section_id')
    )
    op.create_index(op.f('ix_exam_sections_section_id'), 'exam_sections', ['section_id'], unique=False)
    op.create_table('package_transactions',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('transaction_code', sa.String(length=500), nullable=True),
    sa.Column('bank_description', sa.Text(), nullable=True),
    sa.Column('bank_transfer_image', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', 'reject', name='transaction_status_types'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['vip_packages.package_id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['vip_subscriptions.subscription_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_package_transactions_transaction_id'), 'package_transactions', ['transaction_id'], unique=False)
    op.create_table('speaking_answers',
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['speaking_questions.question_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_index(op.f('ix_speaking_answers_answer_id'), 'speaking_answers', ['answer_id'], unique=False)
    op.create_table('writing_tasks',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('part_number', sa.Integer(), nullable=True),
    sa.Column('task_type', sa.Enum('essay', 'report', 'letter', name='task_types'), nullable=True),
    sa.Column('instructions', mysql.LONGTEXT(), nullable=True),
    sa.Column('word_limit', sa.Integer(), nullable=True),
    sa.Column('total_marks', sa.Float(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['exams.exam_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_writing_tasks_task_id'), 'writing_tasks', ['task_id'], unique=False)
    op.create_table('listening_media',
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('audio_file', mysql.LONGBLOB(), nullable=True),
    sa.Column('audio_filename', sa.String(length=255), nullable=True),
    sa.Column('transcript', mysql.LONGTEXT(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['exam_sections.section_id'], ),
    sa.PrimaryKeyConstraint('media_id')
    )
    op.create_index(op.f('ix_listening_media_media_id'), 'listening_media', ['media_id'], unique=False)
    op.create_table('question_groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('question_range', sa.String(length=50), nullable=True),
    sa.Column('group_type', sa.String(length=50), nullable=True),
    sa.Column('order_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['exam_sections.section_id'], ),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_index(op.f('ix_question_groups_group_id'), 'question_groups', ['group_id'], unique=False)
    op.create_table('reading_passages',
    sa.Column('passage_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['exam_sections.section_id'], ),
    sa.PrimaryKeyConstraint('passage_id')
    )
    op.create_index(op.f('ix_reading_passages_passage_id'), 'reading_passages', ['passage_id'], unique=False)
    op.create_table('writing_answers',
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('answer_text', mysql.LONGTEXT(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('is_ai_evaluated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('task_achievement_score', sa.Float(), nullable=True),
    sa.Column('coherence_cohesion_score', sa.Float(), nullable=True),
    sa.Column('lexical_resource_score', sa.Float(), nullable=True),
    sa.Column('grammatical_range_score', sa.Float(), nullable=True),
    sa.Column('mistakes', sa.JSON(), nullable=True),
    sa.Column('improvement_suggestions', sa.JSON(), nullable=True),
    sa.Column('rewritten_essay', mysql.LONGTEXT(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['writing_tasks.task_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_index(op.f('ix_writing_answers_answer_id'), 'writing_answers', ['answer_id'], unique=False)
    op.create_table('questions',
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('question_number', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('question_type', sa.Text(), nullable=True),
    sa.Column('question_text', mysql.LONGTEXT(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.Column('media_url', sa.String(length=255), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['question_groups.group_id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['exam_sections.section_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_index(op.f('ix_questions_question_id'), 'questions', ['question_id'], unique=False)
    op.create_table('listening_answers',
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('student_answer', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.exam_id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_index(op.f('ix_listening_answers_answer_id'), 'listening_answers', ['answer_id'], unique=False)
    op.create_table('question_options',
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('option_text', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.PrimaryKeyConstraint('option_id')
    )
    op.create_index(op.f('ix_question_options_option_id'), 'question_options', ['option_id'], unique=False)
    op.create_table('student_answers',
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('student_answer', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['exam_results.result_id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_index(op.f('ix_student_answers_answer_id'), 'student_answers', ['answer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_answers_answer_id'), table_name='student_answers')
    op.drop_table('student_answers')
    op.drop_index(op.f('ix_question_options_option_id'), table_name='question_options')
    op.drop_table('question_options')
    op.drop_index(op.f('ix_listening_answers_answer_id'), table_name='listening_answers')
    op.drop_table('listening_answers')
    op.drop_index(op.f('ix_questions_question_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_writing_answers_answer_id'), table_name='writing_answers')
    op.drop_table('writing_answers')
    op.drop_index(op.f('ix_reading_passages_passage_id'), table_name='reading_passages')
    op.drop_table('reading_passages')
    op.drop_index(op.f('ix_question_groups_group_id'), table_name='question_groups')
    op.drop_table('question_groups')
    op.drop_index(op.f('ix_listening_media_media_id'), table_name='listening_media')
    op.drop_table('listening_media')
    op.drop_index(op.f('ix_writing_tasks_task_id'), table_name='writing_tasks')
    op.drop_table('writing_tasks')
    op.drop_index(op.f('ix_speaking_answers_answer_id'), table_name='speaking_answers')
    op.drop_table('speaking_answers')
    op.drop_index(op.f('ix_package_transactions_transaction_id'), table_name='package_transactions')
    op.drop_table('package_transactions')
    op.drop_index(op.f('ix_exam_sections_section_id'), table_name='exam_sections')
    op.drop_table('exam_sections')
    op.drop_index(op.f('ix_exam_results_result_id'), table_name='exam_results')
    op.drop_table('exam_results')
    op.drop_table('exam_access_types')
    op.drop_index(op.f('ix_vip_subscriptions_subscription_id'), table_name='vip_subscriptions')
    op.drop_table('vip_subscriptions')
    op.drop_index(op.f('ix_speaking_questions_question_id'), table_name='speaking_questions')
    op.drop_table('speaking_questions')
    op.drop_index(op.f('ix_exams_exam_id'), table_name='exams')
    op.drop_table('exams')
    op.drop_index(op.f('ix_admin_notification_reads_read_id'), table_name='admin_notification_reads')
    op.drop_table('admin_notification_reads')
    op.drop_index(op.f('ix_vip_packages_package_id'), table_name='vip_packages')
    op.drop_table('vip_packages')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_speaking_topics_topic_id'), table_name='speaking_topics')
    op.drop_table('speaking_topics')
    # ### end Alembic commands ###
