"""“add_writing_sample”

Revision ID: a072b68d93e6
Revises: c0eb57ffcae6
Create Date: 2025-11-24 10:03:21.649347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a072b68d93e6'
down_revision: Union[str, None] = 'c0eb57ffcae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('writing_tasks', sa.Column('sample_essay', mysql.LONGTEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('writing_tasks', 'sample_essay')
    # ### end Alembic commands ###
