"""“update_revert_highlight_11-Nov”

Revision ID: ae616baed13f
Revises: 5633c36cc026
Create Date: 2025-11-11 04:56:23.378283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ae616baed13f'
down_revision: Union[str, None] = '5633c36cc026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_highlights_highlight_id'), table_name='user_highlights')
    op.drop_table('user_highlights')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_highlights',
    sa.Column('highlight_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exam_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('result_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('part_number', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('highlighted_text', mysql.TEXT(), nullable=True),
    sa.Column('range_info', mysql.JSON(), nullable=True),
    sa.Column('signature', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.exam_id'], name=op.f('user_highlights_ibfk_1')),
    sa.ForeignKeyConstraint(['result_id'], ['exam_results.result_id'], name=op.f('user_highlights_ibfk_2')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('user_highlights_ibfk_3')),
    sa.PrimaryKeyConstraint('highlight_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_highlights_highlight_id'), 'user_highlights', ['highlight_id'], unique=False)
    # ### end Alembic commands ###
