"""“update_lis_forecast_3”

Revision ID: c0eb57ffcae6
Revises: f139d7b775d7
Create Date: 2025-11-19 09:18:25.180557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0eb57ffcae6'
down_revision: Union[str, None] = 'f139d7b775d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_sections', sa.Column('is_forecast', sa.Boolean(), nullable=True))
    op.add_column('exam_sections', sa.Column('forecast_title', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_sections', 'forecast_title')
    op.drop_column('exam_sections', 'is_forecast')
    # ### end Alembic commands ###
