"""“forecast_logic”

Revision ID: cab02a134f18
Revises: a072b68d93e6
Create Date: 2025-12-29 10:34:48.113497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cab02a134f18'
down_revision: Union[str, None] = 'a072b68d93e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_results', sa.Column('is_forecast', sa.Boolean(), nullable=True))
    op.add_column('exam_results', sa.Column('forecast_part', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_results', 'forecast_part')
    op.drop_column('exam_results', 'is_forecast')
    # ### end Alembic commands ###
