"""“update_speaking_tables”

Revision ID: cc569140ed5c
Revises: ae616baed13f
Create Date: 2025-11-17 10:50:22.907471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cc569140ed5c'
down_revision: Union[str, None] = 'ae616baed13f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speaking_materials',
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('part_type', sa.Enum('part1', 'part2_3', name='speaking_part_types'), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('material_id')
    )
    op.create_index(op.f('ix_speaking_materials_material_id'), 'speaking_materials', ['material_id'], unique=False)
    op.drop_index('ix_user_highlights_highlight_id', table_name='user_highlights')
    op.drop_table('user_highlights')
    op.drop_index('ix_speaking_answers_answer_id', table_name='speaking_answers')
    op.drop_table('speaking_answers')
    op.drop_index('ix_speaking_questions_question_id', table_name='speaking_questions')
    op.drop_table('speaking_questions')
    op.drop_index('ix_speaking_topics_topic_id', table_name='speaking_topics')
    op.drop_table('speaking_topics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speaking_topics',
    sa.Column('topic_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('topic_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_speaking_topics_topic_id', 'speaking_topics', ['topic_id'], unique=False)
    op.create_table('speaking_questions',
    sa.Column('question_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('topic_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question_text', mysql.TEXT(), nullable=False),
    sa.Column('sample_answer', mysql.TEXT(), nullable=False),
    sa.Column('order_number', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('part_type', mysql.ENUM('part1', 'part2', 'part3'), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['speaking_topics.topic_id'], name='speaking_questions_ibfk_1'),
    sa.PrimaryKeyConstraint('question_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_speaking_questions_question_id', 'speaking_questions', ['question_id'], unique=False)
    op.create_table('speaking_answers',
    sa.Column('answer_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answer_text', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['speaking_questions.question_id'], name='speaking_answers_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='speaking_answers_ibfk_2'),
    sa.PrimaryKeyConstraint('answer_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_speaking_answers_answer_id', 'speaking_answers', ['answer_id'], unique=False)
    op.create_table('user_highlights',
    sa.Column('highlight_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exam_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('result_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('part_number', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('highlighted_text', mysql.TEXT(), nullable=True),
    sa.Column('range_info', mysql.JSON(), nullable=True),
    sa.Column('signature', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.exam_id'], name='user_highlights_ibfk_1'),
    sa.ForeignKeyConstraint(['result_id'], ['exam_results.result_id'], name='user_highlights_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='user_highlights_ibfk_3'),
    sa.PrimaryKeyConstraint('highlight_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_user_highlights_highlight_id', 'user_highlights', ['highlight_id'], unique=False)
    op.drop_index(op.f('ix_speaking_materials_material_id'), table_name='speaking_materials')
    op.drop_table('speaking_materials')
    # ### end Alembic commands ###
