"""update_17_July_2025

Revision ID: eab0f673cc58
Revises: 0595f4f90b6d
Create Date: 2025-07-17 16:31:34.415088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eab0f673cc58'
down_revision: Union[str, None] = '0595f4f90b6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_notifications', sa.Column('image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_notifications', 'image_url')
    # ### end Alembic commands ###
